# 插件的唯一网址，服务器插件需配置
插件网址: /yz/v3/mcqq
# 插件的唯一端口，服务器
插件端口: 1234
# 群内使用服务器命令的前缀
命令前缀: /
# 群信息转发至服务器时，玩家名字和信息中间的介词
群转服: 表示
# 服务器信息转发至群时，玩家名字和信息中间的介词
服转群: 说
# 转发信息违禁词检测
信息违禁词:
  - 傻逼
  - 脑残
  - 操你妈
  - fuck
  - shit
  - 妈的
  - 草泥马
  - cnm
# 违禁词替换文本
违禁词替换: 表达了情绪
# 默认群配置 请勿删除
群组配置:
  # 需同步消息的群号
  - 群号:
    # 同步至服务器时显示的群名称
    群名称: 默认
    # 消息同步至群聊触发前缀
    前缀: a
    # 消息同步至服务器时是否显示群名
    显示群名: 是
    # 是: 接受所有服务器事件
    同步服务器的所有消息: 否
    # 否: 按下面的事件配置决定接受哪些服务器的事件
    # 当前群组接受哪些服务器开、关服通知（空数组表示不接受任何通知）
    开关服通知: 
      - 服务器名称
    # 当前群组接受哪些服务器玩家加入事件（空数组表示不接受任何通知）
    玩家登入通知:
      - 服务器名称
    # 当前群组接受哪些服务器玩家退出事件（空数组表示不接受任何通知）
    玩家登出通知:
      - 服务器名称
    # 当前群组接受哪些服务器玩家死亡事件（空数组表示不接受任何通知）
    玩家死亡通知:
      - 服务器名称
    # 当前群组接受哪些服务器玩家成就事件（空数组表示不接受任何通知）
    玩家成就通知: 
      - 服务器名称
    # 当前群组接受哪些服务器玩家聊天事件（空数组表示不接受任何通知）
    玩家聊天通知: 
      - 服务器名称
    # 当前群组接受哪些务器玩家命令事件（空数组表示不接受任何通知）
    玩家命令通知:
      - 服务器名称
# 默认服务器配置 请勿删除
服务器配置:
  # 服务器同步至群消息名称，须和服务器插件名称同步
  - 服务器名称: default_server
    # 服务器rcon网址,服务器,默认127.0.0.1
    rcon网址: 
    # 服务器的rcon端口,服务器server.properties文件中复制,按此区分不同服务器
    rcon端口: 
    # 服务器rcon密码,服务器server.properties文件中复制
    rcon密码: password
    # 消息同步至服务器触发前缀
    前缀: a
    # 普通群友可使用的指令列表（空数组表示不接受任何通知），群管理人员可全用
    指令列表:
      - list
      - time set day
      - weather clear
      - gamemode survival
      - gamemode creative